### ISSUE TITLE
草

### ISSUE THREAD

**Issue by xghgj0508** [xiaoxiaodesha/hd_node#6]
你是傻逼吗？安装步骤。在唬弄。草

**Comment by xiaoxiaodesha** [comment]
我并没有唬你，这个本质是修改第三方源码|

**Comment by xiaoxiaodesha** [comment]
就是InsightFace没有安装导致的，
本身是为了解决

**Comment by xiaoxiaodesha** [comment]
Error occurred when executing InsightFaceLoader: No module named 'insightface' 
这个问题
