### ISSUE TITLE
HD Ultimate Upscale Node always shows RED

### ISSUE THREAD

**Issue by nodegraphics** [xiaoxiaodesha/hd_node#8]
I tried to install from scratch, update and fix from comfy manager. But no luck. 
I like to know if there is any solution for this ?

Thank you

![Screenshot - 2024-06-24 00 14 23](https://github.com/xiaoxiaodesha/hd_node/assets/10071439/a2508398-1903-4fa3-bf23-1f0b4115e53e)

![Screenshot - 2024-06-24 00 22 50](https://github.com/xiaoxiaodesha/hd_node/assets/10071439/0bfd9288-c94b-43df-861c-25282c807c32)

**Comment by xiaoxiaodesha** [comment]
你可能不需要这个节点，这个节点是特殊的放大节点

**Comment by nodegraphics** [comment]
what is that even mean "I may not need this node ?"

**Comment by nodegraphics** [comment]
So you want me to "NOT USE IT" and just replace it with something else ?

**Comment by xiaoxiaodesha** [comment]
我这就是超级放大，放大 只放大上半身
